development:
  adapter: postgresql
  encoding: utf8
  database: listing_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: listing_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: listing_production
  pool: 5
  username: 
  password:
